version: '3'

services:
  tor:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/tor.Dockerfile
    networks:
      - epixnet-network
    environment: &tor-environments
      # since we are using tor internally, password doesn't really matter
      TOR_CONTROL_PASSWD: some_password
      TOR_SOCKS_PORT: 9050
      TOR_CONTROL_PORT: 9051

  epixnet:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - epixnet-network
    volumes:
      # NOTE: this refers to docker/data..
      - ./data:/home/service-epixnet/data
    ports:
      - "10042:10042"
      - "127.0.0.1:42222:42222"
    depends_on:
      - tor
    environment:
      TOR_ENABLED: enable
      <<: *tor-environments

  # integrated container with tor
  epixnet-tor:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/znctor.Dockerfile
    networks:
      - epixnet-network
    volumes:
      # NOTE: this refers to docker/data..
      - ./data:/home/service-epixnet/data
    ports:
      - "10042:10042"
      - "127.0.0.1:42222:42222"

networks:
  epixnet-network:
