import UIKit
import WebKit
// Generated by uniffi-bindgen from crates/epix-ffi (see shells/README.md).
import EpixFFI

/// The iOS shell: a browser over the embedded Epix node.
///
/// The Rust core is linked in as a staticlib and called through the generated
/// UniFFI Swift bindings. We boot the node, then drive a WKWebView.
///
/// The surface looks like a browser: an address bar (type `talk.epix`, an
/// `epix1…` address, or any URL) and, Brave-style, the Epix button next to it.
/// The button wears the Tor state as a badge (the desktop extension's colors:
/// gray off, amber connecting, purple ready, green when all traffic routes
/// through Tor) and opens the Epix panel - current xite, Tor status, our onion
/// address - when tapped.
///
/// KNOWN SPIKE (Phase 8b #1): custom-scheme pages in WKWebView are NOT secure
/// contexts (no service workers, no crypto.subtle). This scaffold loads the
/// loopback `http://127.0.0.1` origin directly, which sidesteps the custom
/// scheme but exposes the port. The three escapes to evaluate - the
/// com.apple.developer.web-browser entitlement, iOS 17 proxyConfigurations, or
/// accepting degraded xites - are tracked in PLAN.md (Workstream C correction).
@main
class AppDelegate: UIResponder, UIApplicationDelegate, UITextFieldDelegate {
    var window: UIWindow?
    let node = EpixNode()
    var webView: WKWebView?
    var addressBar: UITextField?
    var torBadge: UIView?
    var torTimer: Timer?
    var urlObservation: NSKeyValueObservation?
    var currentDisplay = ""

    // The dashboard's dark chrome + the desktop extension's icon colors.
    static let chromeBg = UIColor(red: 0x0B / 255.0, green: 0x0E / 255.0, blue: 0x14 / 255.0, alpha: 1)
    static let fieldBg = UIColor(red: 0x1E / 255.0, green: 0x29 / 255.0, blue: 0x3B / 255.0, alpha: 1)
    static let fieldText = UIColor(red: 0xCB / 255.0, green: 0xD5 / 255.0, blue: 0xE1 / 255.0, alpha: 1)
    static let torOff = UIColor(red: 0x64 / 255.0, green: 0x74 / 255.0, blue: 0x8B / 255.0, alpha: 1)
    static let torBoot = UIColor(red: 0xF5 / 255.0, green: 0xC4 / 255.0, blue: 0x50 / 255.0, alpha: 1)
    static let torReady = UIColor(red: 0xA7 / 255.0, green: 0x8B / 255.0, blue: 0xFA / 255.0, alpha: 1)
    static let torRouted = UIColor(red: 0x4A / 255.0, green: 0xDE / 255.0, blue: 0x80 / 255.0, alpha: 1)

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        let controller = UIViewController()
        controller.view = buildBrowserChrome()
        window.rootViewController = controller
        window.makeKeyAndVisible()
        self.window = window

        // The launch URL, if opened via an epix:// link.
        let target = (launchOptions?[.url] as? URL).flatMap(targetFrom) ?? "dashboard.epix"
        currentDisplay = target
        bootNode(target: target)

        // Reflect the Tor state in the button's badge, at the extension's cadence.
        torTimer = Timer.scheduledTimer(withTimeInterval: 5, repeats: true) { [weak self] _ in
            self?.pollTor()
        }
        pollTor()
        return true
    }

    /// The browser chrome: address bar + Epix button on top, the page below.
    private func buildBrowserChrome() -> UIView {
        let container = UIView(frame: UIScreen.main.bounds)
        container.backgroundColor = Self.chromeBg

        let field = UITextField()
        field.attributedPlaceholder = NSAttributedString(
            string: "Type a .epix name or address",
            attributes: [.foregroundColor: Self.torOff]
        )
        field.textColor = Self.fieldText
        field.font = .systemFont(ofSize: 14)
        field.backgroundColor = Self.fieldBg
        field.layer.cornerRadius = 18
        field.autocapitalizationType = .none
        field.autocorrectionType = .no
        field.keyboardType = .URL
        field.returnKeyType = .go
        field.clearButtonMode = .whileEditing
        field.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 14, height: 1))
        field.leftViewMode = .always
        field.delegate = self
        field.translatesAutoresizingMaskIntoConstraints = false
        self.addressBar = field

        // The Epix button (Brave-style): the logo with the Tor state as a
        // badge; tapping opens the Epix panel. The logo ships as epix-icon.png
        // in the bundle (the same asset the Android shell uses), with the
        // system diamond as a fallback if the resource wasn't packaged.
        let button = UIButton(type: .custom)
        if let path = Bundle.main.path(forResource: "epix-icon", ofType: "png"),
            let logo = UIImage(contentsOfFile: path) {
            let size = CGSize(width: 36, height: 36)
            let scaled = UIGraphicsImageRenderer(size: size).image { _ in
                logo.draw(in: CGRect(origin: .zero, size: size))
            }
            button.setImage(scaled.withRenderingMode(.alwaysOriginal), for: .normal)
        } else {
            button.setImage(UIImage(systemName: "diamond.fill"), for: .normal)
            button.tintColor = Self.torReady
        }
        button.accessibilityLabel = "Epix panel"
        button.addTarget(self, action: #selector(showEpixPanel), for: .touchUpInside)
        button.translatesAutoresizingMaskIntoConstraints = false
        let badge = UIView()
        badge.backgroundColor = Self.torOff
        badge.layer.cornerRadius = 6
        badge.layer.borderWidth = 2
        badge.layer.borderColor = Self.chromeBg.cgColor
        badge.isUserInteractionEnabled = false
        badge.translatesAutoresizingMaskIntoConstraints = false
        button.addSubview(badge)
        self.torBadge = badge

        let webView = WKWebView(frame: .zero, configuration: WKWebViewConfiguration())
        webView.translatesAutoresizingMaskIntoConstraints = false
        container.addSubview(webView)
        container.addSubview(field)
        container.addSubview(button)
        self.webView = webView

        // Show `talk.epix/…` in the bar, not the local node plumbing.
        urlObservation = webView.observe(\.url, options: [.new]) { [weak self] _, change in
            guard let self, let url = change.newValue ?? nil else { return }
            if self.addressBar?.isFirstResponder != true {
                self.addressBar?.text = self.friendlyUrl(url.absoluteString)
            }
        }

        let safe = container.safeAreaLayoutGuide
        NSLayoutConstraint.activate([
            field.topAnchor.constraint(equalTo: safe.topAnchor, constant: 6),
            field.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: 8),
            field.heightAnchor.constraint(equalToConstant: 36),
            button.leadingAnchor.constraint(equalTo: field.trailingAnchor, constant: 4),
            button.trailingAnchor.constraint(equalTo: container.trailingAnchor, constant: -4),
            button.centerYAnchor.constraint(equalTo: field.centerYAnchor),
            button.widthAnchor.constraint(equalToConstant: 44),
            button.heightAnchor.constraint(equalToConstant: 44),
            badge.widthAnchor.constraint(equalToConstant: 12),
            badge.heightAnchor.constraint(equalToConstant: 12),
            badge.bottomAnchor.constraint(equalTo: button.bottomAnchor, constant: -5),
            badge.trailingAnchor.constraint(equalTo: button.trailingAnchor, constant: -5),
            webView.topAnchor.constraint(equalTo: field.bottomAnchor, constant: 6),
            webView.leadingAnchor.constraint(equalTo: container.leadingAnchor),
            webView.trailingAnchor.constraint(equalTo: container.trailingAnchor),
            webView.bottomAnchor.constraint(equalTo: container.bottomAnchor),
        ])
        return container
    }

    /// Go: turn what the user typed into somewhere to go.
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        navigate(textField.text ?? "")
        textField.resignFirstResponder()
        return true
    }

    private func navigate(_ input: String) {
        let t = input.trimmingCharacters(in: .whitespaces)
        if t.isEmpty { return }
        let url: String
        if t.hasPrefix("http://") || t.hasPrefix("https://") {
            url = t
        } else if t.hasPrefix("epix://") {
            let host = String(t.dropFirst("epix://".count)).components(separatedBy: "/")[0]
            currentDisplay = host
            url = nodeUrl(host)
        } else if t.hasPrefix("epix1") || t.hasSuffix(".epix") {
            currentDisplay = t
            url = nodeUrl(t)
        } else if t.contains("."), !t.contains(" ") {
            // Looks like a clearnet domain: browse it over https.
            url = "https://\(t)"
        } else {
            // A bare word is a .epix name.
            currentDisplay = "\(t).epix"
            url = nodeUrl("\(t).epix")
        }
        if let u = URL(string: url) {
            webView?.load(URLRequest(url: u))
        }
    }

    private func friendlyUrl(_ url: String) -> String {
        let prefix = "http://127.0.0.1:43110/"
        guard url.hasPrefix(prefix) else { return url }
        var rest = String(url.dropFirst(prefix.count))
        while rest.hasSuffix("/") { rest = String(rest.dropLast()) }
        if let first = rest.components(separatedBy: "/").first, !first.isEmpty {
            currentDisplay = first
        }
        return rest
    }

    /// A tapped epix:// link while running: navigate the web view.
    func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        guard let target = targetFrom(url) else { return false }
        currentDisplay = target
        load(display: target)
        return true
    }

    /// Boot the Rust node off the main thread, then load the local URL.
    private func bootNode(target: String) {
        DispatchQueue.global(qos: .userInitiated).async {
            let dataDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].path
            let config = NodeConfig(
                dataDir: dataDir,
                target: target,
                uiAddr: "127.0.0.1:43110",
                torMode: "enable",
                version: "0.1.0"
            )
            do {
                try self.node.start(config: config)
                DispatchQueue.main.async { self.load(display: target) }
            } catch {
                DispatchQueue.main.async { self.showError("\(error)") }
            }
        }
    }

    /// Same color language as the desktop extension's toolbar icon.
    private static func colorFor(_ st: TorStatus) -> UIColor {
        if st.enabled { return st.status == "Always" ? torRouted : torReady }
        if st.status == "Bootstrapping" { return torBoot }
        return torOff
    }

    /// Fetch the Tor state off the main thread (the call blocks) and tint the badge.
    private func pollTor() {
        DispatchQueue.global(qos: .utility).async {
            let st = self.node.torStatus()
            DispatchQueue.main.async {
                self.torBadge?.backgroundColor = Self.colorFor(st)
            }
        }
    }

    /// The Epix panel: current xite, Tor status, our onion address.
    @objc private func showEpixPanel() {
        DispatchQueue.global(qos: .utility).async {
            let st = self.node.torStatus()
            let onion = self.node.onionAddress()
            var message = ""
            if !self.currentDisplay.isEmpty {
                message += "Xite: \(self.currentDisplay)\n\n"
            }
            if st.enabled {
                message += st.status == "Always"
                    ? "Tor: on - all traffic routed through Tor"
                    : "Tor: ready - onion peers reachable"
            } else if st.status == "Bootstrapping" {
                message += "Tor: connecting…"
            } else if st.status == "Failed" {
                message += "Tor: failed to start"
            } else {
                message += "Tor: off"
            }
            if let onion = onion {
                message += "\n\nYour onion address:\n\(onion).onion"
            }
            DispatchQueue.main.async {
                let alert = UIAlertController(title: "Epix", message: message, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "OK", style: .default))
                self.window?.rootViewController?.present(alert, animated: true)
            }
        }
    }

    private func load(display: String) {
        guard let url = URL(string: nodeUrl(display)) else { return }
        webView?.load(URLRequest(url: url))
    }

    private func nodeUrl(_ name: String) -> String {
        "http://127.0.0.1:43110/\(name)/"
    }

    private func showError(_ message: String) {
        let html = "<body style='font:16px system-ui;padding:2rem;color:#f87171'>Could not start Epix: \(message)</body>"
        webView?.loadHTMLString(html, baseURL: nil)
    }

    /// Pull the xite host out of an `epix://host/path` URL.
    private func targetFrom(_ url: URL) -> String? {
        guard url.scheme == "epix" else { return nil }
        return url.host ?? url.absoluteString
            .replacingOccurrences(of: "epix://", with: "")
            .components(separatedBy: "/").first
    }
}
