import UIKit
import WebKit
// Generated by uniffi-bindgen from crates/epix-ffi (see shells/README.md).
import EpixFFI

/// The iOS shell: a WKWebView browser over the embedded Epix node.
///
/// The Rust core is linked in as a staticlib and called through the generated
/// UniFFI Swift bindings. We boot the node, then load the local node URL in a
/// WKWebView.
///
/// KNOWN SPIKE (Phase 8b #1): custom-scheme pages in WKWebView are NOT secure
/// contexts (no service workers, no crypto.subtle). This scaffold loads the
/// loopback `http://127.0.0.1` origin directly, which sidesteps the custom
/// scheme but exposes the port. The three escapes to evaluate - the
/// com.apple.developer.web-browser entitlement, iOS 17 proxyConfigurations, or
/// accepting degraded xites - are tracked in PLAN.md (Workstream C correction).
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    let node = EpixNode()
    var webView: WKWebView?

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        let controller = UIViewController()
        let webView = WKWebView(frame: .zero, configuration: WKWebViewConfiguration())
        controller.view = webView
        window.rootViewController = controller
        window.makeKeyAndVisible()
        self.window = window
        self.webView = webView

        // The launch URL, if opened via an epix:// link.
        let target = (launchOptions?[.url] as? URL).flatMap(targetFrom) ?? "dashboard.epix"
        bootNode(target: target)
        return true
    }

    /// A tapped epix:// link while running: navigate the web view.
    func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        guard let target = targetFrom(url) else { return false }
        load(display: target)
        return true
    }

    /// Boot the Rust node off the main thread, then load the local URL.
    private func bootNode(target: String) {
        DispatchQueue.global(qos: .userInitiated).async {
            let dataDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].path
            let config = NodeConfig(
                dataDir: dataDir,
                target: target,
                uiAddr: "127.0.0.1:43110",
                torMode: "enable",
                version: "0.1.0"
            )
            do {
                try self.node.start(config: config)
                DispatchQueue.main.async { self.load(display: target) }
            } catch {
                DispatchQueue.main.async { self.showError("\(error)") }
            }
        }
    }

    private func load(display: String) {
        guard let url = URL(string: "http://127.0.0.1:43110/\(display)/") else { return }
        webView?.load(URLRequest(url: url))
    }

    private func showError(_ message: String) {
        let html = "<body style='font:16px system-ui;padding:2rem;color:#f87171'>Could not start Epix: \(message)</body>"
        webView?.loadHTMLString(html, baseURL: nil)
    }

    /// Pull the xite host out of an `epix://host/path` URL.
    private func targetFrom(_ url: URL) -> String? {
        guard url.scheme == "epix" else { return nil }
        return url.host ?? url.absoluteString
            .replacingOccurrences(of: "epix://", with: "")
            .components(separatedBy: "/").first
    }
}
