#!/bin/sh
set -eu
APPDIR="$(CDPATH='' cd -- "$(dirname -- "$(readlink -f -- "$0")")" && pwd)"
export APPDIR
EPIX_FIREFOX="${EPIX_FIREFOX:-$APPDIR/usr/bin/firefox/appimage-firefox}"
export EPIX_FIREFOX
exec "$APPDIR/usr/bin/epix-browser" "$@"
