//! Compute the frozen known-answer vectors for the channel crypto construction
//! and print them as ready-to-paste Rust constants. Run once; the values are
//! then embedded in `tests/vectors.rs` and become a regression lock on the exact
//! primitives/derivations (HKDF-SHA256, HMAC-SHA256, X3DH, tag chain). Any change
//! to the construction changes these and fails the vector test on purpose.
//!
//!   cargo run -q -p epix-pairwise-engine --example gen_vectors

use epix_pairwise_engine::{crypto, curve, keys};

fn h(b: &[u8]) -> String {
    hex::encode(b)
}

fn main() {
    // Fixed, arbitrary inputs.
    let seed_a = [1u8; 32];
    let seed_b = [2u8; 32];
    let eph = [3u8; 32];
    let spk_idx = 2954u32;

    // Primitive KATs.
    let kdf_kat = crypto::kdf32("epix-channel/test/v1", b"salt", b"ikm");
    let mac_kat = crypto::mac(&[7u8; 32], b"data");

    // Identity/prekey derivation.
    let ik_a = keys::ik_priv(&seed_a);
    let ik_a_pub = curve::public_key(&ik_a);
    let spk_b = keys::spk_priv(&seed_b, spk_idx);
    let spk_b_pub = curve::public_key(&spk_b);
    let ik_b = keys::ik_priv(&seed_b);
    let ik_b_pub = curve::public_key(&ik_b);

    // X3DH SK from the three fixed DH values (initiator view).
    let dh1 = curve::dh(&ik_a, &spk_b_pub);
    let dh2 = curve::dh(&eph, &ik_b_pub);
    let dh3 = curve::dh(&eph, &spk_b_pub);
    let mut ikm = Vec::new();
    ikm.extend_from_slice(&dh1);
    ikm.extend_from_slice(&dh2);
    ikm.extend_from_slice(&dh3);
    let sk = crypto::kdf32("epix-channel/x3dh/v1", &[0xFFu8; 32], &ikm);
    let fc_key = crypto::kdf32("epix-channel/fc-hdr/v1", &[9u8; 32], &dh2);

    // Tag chain (tck fixed).
    let tck = [5u8; 32];
    let tag = crypto::mac(&tck, b"tag");
    let hk = crypto::mac(&tck, b"hdr");
    let next_tck = crypto::mac(&tck, b"chain");

    // Chain KDF (ck fixed): mk = MAC(ck, 0x01), ck' = MAC(ck, 0x02).
    let ck = [6u8; 32];
    let mk = crypto::mac(&ck, &[1u8]);
    let ck_next = crypto::mac(&ck, &[2u8]);

    println!("// AUTO-GENERATED by `cargo run --example gen_vectors`. Do not edit by hand.");
    println!("pub const KDF_KAT: &str = \"{}\";", h(&kdf_kat));
    println!("pub const MAC_KAT: &str = \"{}\";", h(&mac_kat));
    println!("pub const IK_A_PRIV: &str = \"{}\";", h(&ik_a));
    println!("pub const IK_A_PUB: &str = \"{}\";", h(&ik_a_pub));
    println!("pub const SPK_B_PRIV: &str = \"{}\";", h(&spk_b));
    println!("pub const SPK_B_PUB: &str = \"{}\";", h(&spk_b_pub));
    println!("pub const IK_B_PUB: &str = \"{}\";", h(&ik_b_pub));
    println!("pub const X3DH_SK: &str = \"{}\";", h(&sk));
    println!("pub const FC_KEY: &str = \"{}\";", h(&fc_key));
    println!("pub const TAG: &str = \"{}\";", h(&tag));
    println!("pub const HK: &str = \"{}\";", h(&hk));
    println!("pub const NEXT_TCK: &str = \"{}\";", h(&next_tck));
    println!("pub const MK: &str = \"{}\";", h(&mk));
    println!("pub const CK_NEXT: &str = \"{}\";", h(&ck_next));
}
