package zone.epix.app

import android.app.AlertDialog
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.view.inputmethod.EditorInfo
import android.view.inputmethod.InputMethodManager
import android.widget.EditText
import android.widget.FrameLayout
import android.widget.ImageButton
import android.widget.LinearLayout
import android.widget.Switch
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import org.mozilla.gecko.util.GeckoBundle
import org.mozilla.geckoview.GeckoPreferenceController
import org.mozilla.geckoview.GeckoResult
import org.mozilla.geckoview.GeckoRuntime
import org.mozilla.geckoview.GeckoSession
import org.mozilla.geckoview.GeckoView
import org.mozilla.geckoview.WebExtension
import org.mozilla.geckoview.WebRequestError
// Generated by uniffi-bindgen from crates/epix-ffi (see shells/README.md).
import uniffi.epix_ffi.EpixNode
import uniffi.epix_ffi.NodeConfig
import uniffi.epix_ffi.NodeState
import uniffi.epix_ffi.TorStatus

/**
 * The Android shell: a browser over the embedded Epix node.
 *
 * The Rust core runs in-process (loaded as a cdylib via the generated UniFFI
 * bindings). We boot the node on a background coroutine, then point GeckoView at
 * the local node URL. `.epix` navigation and the EpixNet #15 CSP/clearnet policy
 * are enforced by the engine (server-side CSP) plus a bundled WebExtension
 * (installBuiltIn + webRequest) - the GeckoView way, since it has no
 * shouldInterceptRequest. That extension is a follow-up.
 *
 * The surface looks like a browser: an address bar (type `talk.epix`, an
 * `epix1…` address, or any URL) and, Brave-style, the Epix icon next to it.
 * The icon wears the Tor state as a badge (the desktop extension's colors:
 * gray off, amber connecting, purple ready, green when all traffic routes
 * through Tor) and opens the Epix panel - current xite, Tor status, our onion
 * address - when tapped.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var geckoView: GeckoView
    private lateinit var session: GeckoSession
    private lateinit var addressBar: EditText
    private lateinit var torBadge: GradientDrawable
    private lateinit var runtime: GeckoRuntime
    private val node = EpixNode()
    private val scope = CoroutineScope(Dispatchers.Main)
    private var canGoBack = false
    private var currentDisplay: String = ""
    /// Route clearnet browsing through the node's Tor SOCKS listener. Default
    /// on (opt-out), like the desktop extension. Persisted across launches.
    private var torClearnet = true
    /// The embedded Epix Wallet (the desktop browser's extension, installed
    /// built-in); tapping the Epix button opens its popup document.
    private var wallet: WebExtension? = null
    private var walletDialog: AlertDialog? = null
    /// The wallet extension opens pages (register, sign approvals) with
    /// tabs.create. On first install it auto-opens its onboarding/register
    /// page, which we do NOT want on launch - the user should land on the
    /// dashboard and reach the wallet only by tapping the Epix button. So we
    /// only present wallet-opened tabs once the user has actually opened the
    /// wallet at least once; the register flow is still reachable from the
    /// wallet popup after that first tap.
    private var walletUserEngaged = false
    /// A GeckoView permission callback parked while the Android runtime
    /// permission dialog (e.g. CAMERA for the wallet's Keystone QR scanner)
    /// is up; resolved in onRequestPermissionsResult.
    private var pendingGeckoPermission: GeckoSession.PermissionDelegate.Callback? = null
    /// A page's file prompt (an <input type=file> tap) parked while the system
    /// document picker is up; resolved in onActivityResult.
    private var pendingFilePrompt: GeckoSession.PromptDelegate.FilePrompt? = null
    private var pendingFileResult: GeckoResult<GeckoSession.PromptDelegate.PromptResponse>? = null
    /// Retries left for a failed load of the node's own UI (see onLoadError).
    private var nodeLoadRetries = 0
    /// Full-screen loading splash (spinning white Epix mark) shown over the
    /// chrome while the node boots and the first page paints; removed on the
    /// first page stop. Mirrors the desktop toolbar spin (EpixNet PR #231).
    private var splashOverlay: View? = null
    /// Set once we ask the session to load the actual node page. The session
    /// opens at about:blank and fires an immediate page-stop for it; without
    /// this guard the splash would vanish before the real page even loads.
    private var nodePageRequested = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        torClearnet = getPreferences(Context.MODE_PRIVATE).getBoolean(PREF_TOR_CLEARNET, true)

        val container = FrameLayout(this)
        container.addView(
            buildBrowserChrome(),
            FrameLayout.LayoutParams(-1, -1),
        )
        splashOverlay = buildSplash().also {
            container.addView(it, FrameLayout.LayoutParams(-1, -1))
        }
        setContentView(container)

        runtime = GeckoRuntime.getDefault(this)
        installWallet()
        session = GeckoSession().apply { open(runtime) }
        session.navigationDelegate = object : GeckoSession.NavigationDelegate {
            override fun onLocationChange(
                session: GeckoSession,
                url: String?,
                perms: MutableList<GeckoSession.PermissionDelegate.ContentPermission>,
                hasUserGesture: Boolean,
            ) {
                if (url != null && !addressBar.hasFocus()) {
                    addressBar.setText(friendlyUrl(url))
                }
            }

            override fun onCanGoBack(session: GeckoSession, value: Boolean) {
                canGoBack = value
            }

            override fun onLoadError(
                session: GeckoSession,
                uri: String?,
                error: WebRequestError,
            ): GeckoResult<String>? {
                // GeckoView renders nothing on a load error unless the app
                // supplies an error page, so a refused connection to the node
                // (its UI still coming up) used to read as a blank app. Wait
                // for the port and retry; only if the node stays unreachable
                // show a real error page.
                if (uri == null || !uri.startsWith(NODE_BASE)) return null
                if (nodeLoadRetries < MAX_NODE_LOAD_RETRIES) {
                    nodeLoadRetries++
                    scope.launch {
                        awaitUiPort()
                        session.loadUri(uri)
                    }
                    return null
                }
                return GeckoResult.fromValue(errorPage())
            }
        }
        session.progressDelegate = object : GeckoSession.ProgressDelegate {
            override fun onPageStop(session: GeckoSession, success: Boolean) {
                // A page made it through: later transient errors get a fresh
                // retry budget.
                if (success) nodeLoadRetries = 0
                // The first real page (dashboard or the error page) is up, so
                // the boot/connect wait is over - drop the loading splash. Skip
                // the session's initial about:blank stop (nodePageRequested).
                if (nodePageRequested) hideSplash()
            }
        }
        // GeckoView draws no UI of its own for content prompts: without a
        // PromptDelegate, <select> dropdowns and JS alert/confirm/prompt taps
        // silently do nothing (the Config page's dropdowns and reset
        // confirms). WKWebView handles these natively on iOS; this is the
        // Android equivalent, backed by plain AlertDialogs.
        session.promptDelegate = buildPromptDelegate()
        geckoView.setSession(session)
        // The page, not the address bar, starts focused - otherwise the
        // keyboard pops over the app on every launch.
        geckoView.requestFocus()

        // The xite to open: from an epix:// launch intent, else the dashboard.
        val target = intentTarget(intent) ?: "dashboard.epix"

        scope.launch {
            // Apply the saved clearnet-through-Tor routing before the first page
            // load, so clearnet requests are proxied from the start. Loopback
            // (the dashboard and every .epix page) is exempt, so this is safe to
            // set before the node is up.
            applyClearnetRouting()
            val display = bootNode(target)
            // Load the dashboard even if boot reported a problem: the node
            // serves its own loading/error wrapper on loopback, which is more
            // useful than a blank page and lets the user retry.
            currentDisplay = display ?: target
            // Don't hand GeckoView the URL until loopback actually accepts
            // (the desktop launcher's wait_for_port): a refused first
            // connection renders as a silent blank page. The node now binds
            // before start() returns, so this passes immediately - it guards
            // the boot-failed path and anything else that delays the bind.
            // From here the next page-stop is a real page, so let it drop the
            // splash (about:blank already came and went).
            nodePageRequested = true
            if (awaitUiPort()) {
                session.loadUri(nodeUrl(currentDisplay))
            } else {
                session.loadUri(errorPage())
            }
        }

        // Reflect the Tor state in the icon's badge, at the extension's cadence.
        scope.launch {
            while (true) {
                torStatus()?.let { torBadge.setColor(colorFor(it)) }
                delay(5_000)
            }
        }
    }

    /** Content prompt UI (selects, alert/confirm/prompt) over AlertDialogs. */
    private fun buildPromptDelegate() = object : GeckoSession.PromptDelegate {
        /// A prompt must be answered exactly once, but a dialog's dismiss
        /// listener also runs after a button click. The response is built
        /// lazily INSIDE the guard: even `prompt.dismiss()` throws
        /// "Cannot confirm/dismiss a Prompt twice" once the prompt is
        /// complete, so it must not be evaluated as a call argument (that
        /// exact pattern crashed the app on every confirmed dialog, e.g.
        /// deleting a backup).
        fun done(
            res: GeckoResult<GeckoSession.PromptDelegate.PromptResponse>,
            prompt: GeckoSession.PromptDelegate.BasePrompt,
            respond: () -> GeckoSession.PromptDelegate.PromptResponse,
        ) {
            if (prompt.isComplete) return
            runCatching { res.complete(respond()) }
        }

        override fun onAlertPrompt(
            session: GeckoSession,
            prompt: GeckoSession.PromptDelegate.AlertPrompt,
        ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
            val res = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
            val dialog = AlertDialog.Builder(this@MainActivity)
                .setTitle(prompt.title)
                .setMessage(prompt.message)
                .setPositiveButton(android.R.string.ok, null)
                .create()
            dialog.setOnDismissListener { done(res, prompt) { prompt.dismiss() } }
            dialog.show()
            return res
        }

        override fun onButtonPrompt(
            session: GeckoSession,
            prompt: GeckoSession.PromptDelegate.ButtonPrompt,
        ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
            val res = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
            val dialog = AlertDialog.Builder(this@MainActivity)
                .setTitle(prompt.title)
                .setMessage(prompt.message)
                .setPositiveButton(android.R.string.ok) { _, _ ->
                    done(res, prompt) {
                        prompt.confirm(GeckoSession.PromptDelegate.ButtonPrompt.Type.POSITIVE)
                    }
                }
                .setNegativeButton(android.R.string.cancel) { _, _ ->
                    done(res, prompt) {
                        prompt.confirm(GeckoSession.PromptDelegate.ButtonPrompt.Type.NEGATIVE)
                    }
                }
                .create()
            dialog.setOnDismissListener { done(res, prompt) { prompt.dismiss() } }
            dialog.show()
            return res
        }

        override fun onTextPrompt(
            session: GeckoSession,
            prompt: GeckoSession.PromptDelegate.TextPrompt,
        ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
            val res = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
            val input = EditText(this@MainActivity).apply { setText(prompt.defaultValue ?: "") }
            val pad = (16 * resources.displayMetrics.density).toInt()
            val wrap = FrameLayout(this@MainActivity).apply {
                setPadding(pad, 0, pad, 0)
                addView(input)
            }
            val dialog = AlertDialog.Builder(this@MainActivity)
                .setTitle(prompt.title)
                .setMessage(prompt.message)
                .setView(wrap)
                .setPositiveButton(android.R.string.ok) { _, _ ->
                    done(res, prompt) { prompt.confirm(input.text.toString()) }
                }
                .setNegativeButton(android.R.string.cancel, null)
                .create()
            dialog.setOnDismissListener { done(res, prompt) { prompt.dismiss() } }
            dialog.show()
            return res
        }

        override fun onChoicePrompt(
            session: GeckoSession,
            prompt: GeckoSession.PromptDelegate.ChoicePrompt,
        ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
            val res = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
            // Flatten one optgroup level; our pages only use flat selects.
            val flat = mutableListOf<GeckoSession.PromptDelegate.ChoicePrompt.Choice>()
            for (c in prompt.choices) {
                val subs = c.items
                if (subs.isNullOrEmpty()) flat.add(c) else flat.addAll(subs)
            }
            val labels = flat.map { it.label }.toTypedArray()
            val builder = AlertDialog.Builder(this@MainActivity).setTitle(prompt.title)
            if (prompt.type == GeckoSession.PromptDelegate.ChoicePrompt.Type.MULTIPLE) {
                val checked = BooleanArray(flat.size) { flat[it].selected }
                builder.setMultiChoiceItems(labels, checked) { _, which, isChecked ->
                    checked[which] = isChecked
                }
                builder.setPositiveButton(android.R.string.ok) { _, _ ->
                    val ids = flat.filterIndexed { i, _ -> checked[i] }.map { it.id }.toTypedArray()
                    done(res, prompt) { prompt.confirm(ids) }
                }
                builder.setNegativeButton(android.R.string.cancel, null)
            } else {
                val selected = flat.indexOfFirst { it.selected }
                builder.setSingleChoiceItems(labels, selected) { dialog, which ->
                    done(res, prompt) { prompt.confirm(flat[which]) }
                    dialog.dismiss()
                }
            }
            val dialog = builder.create()
            dialog.setOnDismissListener { done(res, prompt) { prompt.dismiss() } }
            dialog.show()
            return res
        }

        override fun onFilePrompt(
            session: GeckoSession,
            prompt: GeckoSession.PromptDelegate.FilePrompt,
        ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
            // GeckoView draws no file picker either: without this, tapping a
            // page's file input (e.g. Backup & Restore's upload) does nothing.
            // Hand off to the system document picker; the result comes back in
            // onActivityResult.
            val res = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
            pendingFilePrompt = prompt
            pendingFileResult = res
            val intent = Intent(Intent.ACTION_GET_CONTENT).apply {
                addCategory(Intent.CATEGORY_OPENABLE)
                // No mime filter: downloaded backups often carry a generic
                // type, and a strict filter would gray them out. The node
                // validates the file server-side anyway.
                type = "*/*"
                if (prompt.type == GeckoSession.PromptDelegate.FilePrompt.Type.MULTIPLE) {
                    putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
                }
            }
            @Suppress("DEPRECATION")
            startActivityForResult(intent, FILE_PICK_REQUEST)
            return res
        }
    }

    /** The system file picker's answer for a parked onFilePrompt. */
    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        @Suppress("DEPRECATION")
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode != FILE_PICK_REQUEST) return
        val prompt = pendingFilePrompt ?: return
        val res = pendingFileResult ?: return
        pendingFilePrompt = null
        pendingFileResult = null
        if (prompt.isComplete) return
        // A multi-select answer arrives as clipData; a single pick as data.
        val uris = mutableListOf<Uri>()
        data?.clipData?.let { clip -> for (i in 0 until clip.itemCount) uris.add(clip.getItemAt(i).uri) }
        data?.data?.takeIf { uris.isEmpty() }?.let { uris.add(it) }
        if (resultCode != RESULT_OK || uris.isEmpty()) {
            runCatching { res.complete(prompt.dismiss()) }
            return
        }
        // Gecko cannot open a picker's content:// grant (its file delegate
        // fails with NS_ERROR_FILE_UNRECOGNIZED_PATH and the input stays
        // empty), so copy each pick into the app cache and hand Gecko real
        // file:// URIs. Copied off the main thread - a backup can be huge.
        scope.launch {
            val files = withContext(Dispatchers.IO) {
                val dir = java.io.File(cacheDir, "picked")
                dir.deleteRecursively()
                dir.mkdirs()
                uris.mapNotNull { uri -> copyPickedFile(uri, dir) }
            }
            runCatching {
                when {
                    files.isEmpty() -> res.complete(prompt.dismiss())
                    files.size == 1 ->
                        res.complete(prompt.confirm(this@MainActivity, Uri.fromFile(files[0])))
                    else -> res.complete(
                        prompt.confirm(
                            this@MainActivity,
                            files.map { Uri.fromFile(it) }.toTypedArray(),
                        ),
                    )
                }
            }
        }
    }

    /** Copy one picked content:// item into `dir`, keeping its display name. */
    private fun copyPickedFile(uri: Uri, dir: java.io.File): java.io.File? = runCatching {
        val name = (queryDisplayName(uri) ?: "upload.bin").replace('/', '_')
        val out = java.io.File(dir, name)
        contentResolver.openInputStream(uri)!!.use { input ->
            out.outputStream().use { input.copyTo(it) }
        }
        out
    }.getOrNull()

    /** The user-facing file name behind a content:// Uri, if the provider says. */
    private fun queryDisplayName(uri: Uri): String? = runCatching {
        contentResolver.query(uri, null, null, null, null)?.use { c ->
            val i = c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME)
            if (c.moveToFirst() && i >= 0) c.getString(i) else null
        }
    }.getOrNull()

    /** Hardware/gesture back navigates the page history first. */
    @Deprecated("Deprecated in Java")
    override fun onBackPressed() {
        if (canGoBack) session.goBack() else @Suppress("DEPRECATION") super.onBackPressed()
    }

    /** A second epix:// link while running: navigate the existing session. */
    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        val target = intentTarget(intent) ?: return
        currentDisplay = target
        session.loadUri(nodeUrl(target))
    }

    /** The browser chrome: address bar + Epix icon on top, the page below. */
    private fun buildBrowserChrome(): View {
        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            fitsSystemWindows = true
            setBackgroundColor(COLOR_CHROME_BG)
        }

        val bar = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            setPadding(dp(8), dp(6), dp(4), dp(6))
        }

        addressBar = EditText(this).apply {
            hint = "Search or type a .epix name"
            setHintTextColor(COLOR_HINT)
            setTextColor(COLOR_TEXT)
            textSize = 14f
            isSingleLine = true
            inputType = android.text.InputType.TYPE_TEXT_VARIATION_URI
            imeOptions = EditorInfo.IME_ACTION_GO
            setPadding(dp(14), dp(8), dp(14), dp(8))
            background = GradientDrawable().apply {
                cornerRadius = dp(18).toFloat()
                setColor(COLOR_FIELD_BG)
            }
            setSelectAllOnFocus(true)
            setOnEditorActionListener { _, actionId, _ ->
                if (actionId == EditorInfo.IME_ACTION_GO) {
                    navigate(text.toString())
                    true
                } else {
                    false
                }
            }
        }
        bar.addView(addressBar, LinearLayout.LayoutParams(0, -2, 1f))

        // The Epix button (Brave-style): the logo with the Tor state as a
        // badge; tapping opens the Epix panel.
        torBadge = GradientDrawable().apply {
            shape = GradientDrawable.OVAL
            setColor(COLOR_OFF)
            setStroke(dp(2), COLOR_CHROME_BG)
        }
        val icon = android.widget.ImageView(this).apply {
            // The white Epix mark on a dark disc (the disc is the chrome color,
            // so it reads as a clean white mark) - matches the desktop browser's
            // reskinned toolbar icon (EpixNet PR #231).
            setImageResource(R.drawable.epix_badge_white)
            scaleType = android.widget.ImageView.ScaleType.FIT_CENTER
            adjustViewBounds = true
        }
        val badge = View(this).apply { background = torBadge }
        val holder = FrameLayout(this).apply {
            contentDescription = "Epix wallet"
            addView(icon, FrameLayout.LayoutParams(dp(36), dp(36), Gravity.CENTER))
            addView(
                badge,
                FrameLayout.LayoutParams(dp(13), dp(13), Gravity.BOTTOM or Gravity.END).apply {
                    bottomMargin = dp(3)
                    marginEnd = dp(3)
                },
            )
            // Tap opens the wallet (Brave-style); its shield carries the same
            // Tor/I2P panel. Long-press (or no wallet) opens the plain panel.
            setOnClickListener {
                wallet?.let { showWalletPopup(it) } ?: showEpixPanel()
            }
            setOnLongClickListener {
                showEpixPanel()
                true
            }
        }
        bar.addView(holder, LinearLayout.LayoutParams(dp(44), dp(44)))

        root.addView(bar, LinearLayout.LayoutParams(-1, -2))
        geckoView = GeckoView(this)
        // Dark until the page's first paint; GeckoView otherwise flashes
        // white while the node boots and the page loads.
        geckoView.coverUntilFirstPaint(COLOR_CHROME_BG)
        root.addView(geckoView, LinearLayout.LayoutParams(-1, 0, 1f))
        return root
    }

    /**
     * The loading splash: the white Epix mark spinning on the dark chrome
     * background, shown from launch until the first page paints. Mirrors the
     * desktop browser's spinning toolbar icon (EpixNet PR #231) - on a cold
     * start the node bootstraps Tor for tens of seconds, so this covers that
     * wait instead of a blank dark screen.
     */
    private fun buildSplash(): View {
        val overlay = FrameLayout(this).apply {
            setBackgroundColor(COLOR_CHROME_BG)
            // Swallow taps so the chrome behind the splash stays inert while it
            // shows (e.g. the address bar can't be focused mid-boot).
            isClickable = true
        }
        val mark = android.widget.ImageView(this).apply {
            setImageResource(R.drawable.epix_mark_white)
            scaleType = android.widget.ImageView.ScaleType.FIT_CENTER
            // A steady continuous spin (compositor-driven), one turn every
            // 1.2s, for as long as the node is coming up.
            startAnimation(
                android.view.animation.RotateAnimation(
                    0f,
                    360f,
                    android.view.animation.Animation.RELATIVE_TO_SELF,
                    0.5f,
                    android.view.animation.Animation.RELATIVE_TO_SELF,
                    0.5f,
                ).apply {
                    duration = 1200
                    repeatCount = android.view.animation.Animation.INFINITE
                    interpolator = android.view.animation.LinearInterpolator()
                },
            )
        }
        overlay.addView(mark, FrameLayout.LayoutParams(dp(96), dp(96), Gravity.CENTER))
        return overlay
    }

    /** Fade the loading splash out and remove it. Idempotent. */
    private fun hideSplash() {
        val overlay = splashOverlay ?: return
        splashOverlay = null
        overlay.animate()
            .alpha(0f)
            .setDuration(250)
            .withEndAction {
                overlay.clearAnimation()
                (overlay.parent as? android.view.ViewGroup)?.removeView(overlay)
            }
            .start()
    }

    /** Turn what the user typed into somewhere to go. */
    private fun navigate(input: String) {
        val t = input.trim()
        if (t.isEmpty()) return
        val url = when {
            // A leading "?" always searches (the Firefox convention), even
            // for something that would otherwise parse as an address.
            t.startsWith("?") -> searchUrl(t.removePrefix("?"))
            t.startsWith("http://") || t.startsWith("https://") -> t
            t.startsWith("epix://") -> {
                val host = t.removePrefix("epix://").substringBefore('/')
                currentDisplay = host
                nodeUrl(host)
            }
            // Only explicit xite addresses go to the resolver: epix1... or
            // something.epix. A bare word is a search, not an implied .epix.
            t.startsWith("epix1") || t.endsWith(".epix") -> {
                currentDisplay = t
                nodeUrl(t)
            }
            // Looks like a clearnet domain: browse it over https.
            t.contains('.') && !t.contains(' ') -> "https://$t"
            // Everything else - bare words, phrases - searches DuckDuckGo.
            else -> searchUrl(t)
        }
        session.loadUri(url)
        addressBar.clearFocus()
        (getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager)
            .hideSoftInputFromWindow(addressBar.windowToken, 0)
    }

    /** A DuckDuckGo search for typed input that is not an address. */
    private fun searchUrl(query: String): String =
        SEARCH_BASE + java.net.URLEncoder.encode(query.trim(), "UTF-8")

    /** Show `talk.epix/…` in the bar, not the local node plumbing. */
    private fun friendlyUrl(url: String): String {
        val prefix = "$NODE_BASE/"
        if (!url.startsWith(prefix)) return url
        val rest = url.removePrefix(prefix).trimEnd('/')
        rest.substringBefore('/').takeIf { it.isNotEmpty() }?.let { currentDisplay = it }
        return rest
    }

    /** Boot the node off the main thread; return the display name to open. */
    private suspend fun bootNode(target: String): String? = withContext(Dispatchers.IO) {
        try {
            val config = NodeConfig(
                dataDir = filesDir.absolutePath,
                target = target,
                uiAddr = "127.0.0.1:$UI_PORT",
                torMode = "enable",
                version = BuildConfig.VERSION_NAME,
            )
            node.start(config)
            if (node.state() == NodeState.SERVING) target else null
        } catch (e: Exception) {
            // Field reports of a blank first screen were undiagnosable while
            // this was swallowed; the error page + logcat now carry it.
            android.util.Log.e("EpixNode", "node start failed", e)
            null
        }
    }

    /**
     * Poll the node's UI port until it accepts a TCP connection, up to ~15s -
     * the mobile counterpart of the desktop launcher's wait_for_port. Returns
     * whether the port came up.
     */
    private suspend fun awaitUiPort(): Boolean = withContext(Dispatchers.IO) {
        repeat(60) {
            val up = runCatching {
                java.net.Socket().use {
                    it.connect(java.net.InetSocketAddress("127.0.0.1", UI_PORT), 250)
                }
            }.isSuccess
            if (up) return@withContext true
            delay(250)
        }
        false
    }

    /** An inline page for when the node stays unreachable - never a blank app. */
    private fun errorPage(): String {
        val html = """
            <html><head><meta name="viewport" content="width=device-width, initial-scale=1"></head>
            <body style="background:#0b0e14;color:#cbd5e1;font-family:sans-serif;margin:0;
                         display:flex;align-items:center;justify-content:center;height:100vh">
            <div style="text-align:center;padding:24px;max-width:26em">
              <h2 style="color:#e2e8f0">EpixNet could not start</h2>
              <p>The embedded node is not answering. Close the app fully and
                 reopen it; if this keeps happening, please report a bug at
                 github.com/EpixZone/EpixNet.</p>
            </div></body></html>
        """.trimIndent()
        return "data:text/html;base64," +
            android.util.Base64.encodeToString(html.toByteArray(), android.util.Base64.NO_WRAP)
    }

    /** The node's Tor state, fetched off the main thread (the call blocks). */
    private suspend fun torStatus(): TorStatus? = withContext(Dispatchers.IO) {
        runCatching { node.torStatus() }.getOrNull()
    }

    /**
     * Same color language as the desktop extension's toolbar icon: green when
     * Tor is on AND clearnet is routed through it, purple when Tor is ready but
     * clearnet goes direct, amber connecting, gray off.
     */
    private fun colorFor(st: TorStatus): Int = when {
        st.enabled -> if (torClearnet) COLOR_ROUTED else COLOR_READY
        st.status == "Bootstrapping" -> COLOR_BOOT
        else -> COLOR_OFF
    }

    /**
     * The Epix panel: current xite, Tor status, our onion address, and the
     * "route clearnet through Tor" switch (the desktop extension's popup).
     */
    private fun showEpixPanel() {
        scope.launch {
            val st = torStatus()
            val onion = withContext(Dispatchers.IO) {
                runCatching { node.onionAddress() }.getOrNull()
            }
            val torLine = when {
                st == null -> "Tor: unknown"
                st.enabled && torClearnet -> "Tor: on - clearnet routed through Tor"
                st.enabled -> "Tor: ready - onion peers reachable"
                st.status == "Bootstrapping" -> "Tor: connecting…"
                st.status == "Failed" -> "Tor: failed to start"
                else -> "Tor: off"
            }

            val pad = dp(20)
            val layout = LinearLayout(this@MainActivity).apply {
                orientation = LinearLayout.VERTICAL
                setPadding(pad, dp(12), pad, 0)
            }
            if (currentDisplay.isNotEmpty()) {
                layout.addView(label("Xite: $currentDisplay"))
            }
            layout.addView(label(torLine))
            if (onion != null) {
                layout.addView(label("\nYour onion address:\n$onion.onion"))
            }
            val row = LinearLayout(this@MainActivity).apply {
                orientation = LinearLayout.HORIZONTAL
                gravity = Gravity.CENTER_VERTICAL
                setPadding(0, dp(14), 0, 0)
            }
            row.addView(
                label("Route clearnet through Tor"),
                LinearLayout.LayoutParams(0, -2, 1f),
            )
            val toggle = Switch(this@MainActivity).apply {
                isChecked = torClearnet
                setOnCheckedChangeListener { _, checked -> setTorClearnet(checked) }
            }
            row.addView(toggle)
            layout.addView(row)

            AlertDialog.Builder(this@MainActivity)
                .setTitle("Epix")
                .setView(layout)
                .setPositiveButton("OK", null)
                .show()
        }
    }

    /**
     * Install the bundled Epix Wallet WebExtension (the same forked-Keplr
     * build the desktop browser embeds, staged into assets by gradle's
     * `stageWalletExt`) and wire up its two host hooks:
     *
     * - Native messaging: the wallet's background bridge sends the desktop
     *   `zone.epix.nmh` commands; here the app itself is the host, answering
     *   from the in-process node (status over loopback, the clearnet toggle
     *   and per-site allowances from this activity's state).
     * - The toolbar action: tapping the Epix button clicks it, and the popup
     *   session it requests is shown in a dialog over the browser.
     */
    private fun installWallet() {
        runtime.webExtensionController
            .ensureBuiltIn("resource://android/assets/extensions/wallet/", WALLET_EXT_ID)
            .accept({ ext ->
                if (ext == null) return@accept
                wallet = ext
                ext.setMessageDelegate(nmhDelegate, NMH_NAME)
                ext.setActionDelegate(walletActionDelegate)
                // The wallet opens full pages (register, sign approvals) with
                // tabs.create; render those as near-full-screen sheets. The
                // app loads the URL itself (GeckoView hands it over raw, and
                // extension-relative paths like "/register.html" need the
                // moz-extension base put back).
                ext.tabDelegate = object : WebExtension.TabDelegate {
                    override fun onNewTab(
                        source: WebExtension,
                        details: WebExtension.CreateTabDetails,
                    ): GeckoResult<GeckoSession>? {
                        // Suppress the wallet's first-run auto-open (register
                        // page) so launch lands on the dashboard. Once the user
                        // has opened the wallet, its tabs (register, approvals)
                        // are shown normally.
                        if (!walletUserEngaged) {
                            return null
                        }
                        val session = openPopupSession(heightFraction = 0.95)
                        val url = details.url ?: ""
                        val resolved = when {
                            url.isEmpty() -> null
                            url.contains("://") -> url
                            else ->
                                source.metaData.baseUrl.trimEnd('/') +
                                    (if (url.startsWith("/")) url else "/$url")
                        }
                        resolved?.let { session.loadUri(it) }
                        return GeckoResult.fromValue(session)
                    }
                }
            }, { e ->
                android.util.Log.w("EpixWallet", "wallet install failed", e)
            })
    }

    /** The app-side native-messaging host: the desktop `epix-nmh` commands. */
    private val nmhDelegate = object : WebExtension.MessageDelegate {
        override fun onMessage(
            nativeApp: String,
            message: Any,
            sender: WebExtension.MessageSender,
        ): GeckoResult<Any>? {
            val req = message as? JSONObject ?: return null
            val result = GeckoResult<Any>()
            // The response rides Gecko's EventDispatcher, which only accepts
            // its own bundle type, not JSONObject ("Invalid event data").
            scope.launch {
                result.complete(GeckoBundle.fromJSONObject(handleNmh(req)))
            }
            return result
        }
    }

    /**
     * GeckoView's message bridge rejects JSON null values ("Invalid event
     * data"); the node's status JSON uses them for absent addresses. Absent
     * key and null mean the same to the wallet, so drop them.
     */
    private fun stripNulls(o: JSONObject): JSONObject {
        val out = JSONObject()
        for (key in o.keys()) {
            val v = o.get(key)
            if (v == JSONObject.NULL) continue
            out.put(key, if (v is JSONObject) stripNulls(v) else v)
        }
        return out
    }

    /** Answer one native-host command with the same JSON shapes as epix-nmh. */
    private suspend fun handleNmh(req: JSONObject): JSONObject =
        stripNulls(handleNmhRaw(req))

    private suspend fun handleNmhRaw(req: JSONObject): JSONObject {
        return when (req.optString("cmd")) {
            "status" -> withContext(Dispatchers.IO) {
                try {
                    val text = java.net.URL("$NODE_BASE/EpixNet-Internal/Status")
                        .openConnection()
                        .apply { connectTimeout = 2_000; readTimeout = 2_000 }
                        .getInputStream()
                        .bufferedReader()
                        .readText()
                    JSONObject(text)
                } catch (e: Exception) {
                    JSONObject().put("serving", false)
                }
            }.put("ui_port", UI_PORT).put("tor_clearnet", torClearnet)
            "getTorClearnet" -> JSONObject().put("on", torClearnet)
            "setTorClearnet" -> {
                val on = req.optBoolean("on", false)
                setTorClearnet(on)
                JSONObject().put("ok", true).put("on", on)
            }
            "getClearnetAllow" ->
                JSONObject().put("allow", allowedSites().contains(req.optString("site")))
            "setClearnetAllow" -> {
                val site = req.optString("site")
                val sites = allowedSites().toMutableSet()
                if (req.optBoolean("allow")) sites.add(site) else sites.remove(site)
                getPreferences(Context.MODE_PRIVATE).edit()
                    .putStringSet(PREF_CLEARNET_ALLOW, sites).apply()
                JSONObject().put("ok", true)
            }
            "listClearnetAllow" ->
                JSONObject().put("sites", JSONArray(allowedSites().toList()))
            "openConfig" -> {
                // Close the wallet sheet and point the browser at the node's
                // config page (the dashboard's Config lives at the UI origin).
                withContext(Dispatchers.Main) {
                    walletDialog?.dismiss()
                    currentDisplay = "Config"
                    session.loadUri("$NODE_BASE/Config")
                }
                JSONObject().put("ok", true)
            }
            else -> JSONObject().put("error", "unknown command: ${req.optString("cmd")}")
        }
    }

    /** Sites the user allowed to reach clearnet from a `.epix` page. */
    private fun allowedSites(): Set<String> =
        getPreferences(Context.MODE_PRIVATE).getStringSet(PREF_CLEARNET_ALLOW, emptySet())!!

    /**
     * The extension side of popups: if the wallet itself asks to open or
     * toggle its popup, give it a session rendered in the same dialog. (The
     * Epix button does not go through the Action - it loads the popup
     * document directly, see [showWalletPopup].)
     */
    private val walletActionDelegate = object : WebExtension.ActionDelegate {
        override fun onTogglePopup(
            extension: WebExtension,
            action: WebExtension.Action,
        ): GeckoResult<GeckoSession>? {
            walletUserEngaged = true
            walletDialog?.let {
                it.dismiss()
                return null
            }
            return GeckoResult.fromValue(openPopupSession())
        }

        override fun onOpenPopup(
            extension: WebExtension,
            action: WebExtension.Action,
        ): GeckoResult<GeckoSession>? {
            walletUserEngaged = true
            return GeckoResult.fromValue(openPopupSession())
        }
    }

    /**
     * Camera access for the wallet's Keystone QR scanner. Set only on the
     * wallet's popup sessions, and media is granted only to the extension's
     * own pages - regular browsing keeps the default (no camera).
     */
    private val walletPermissionDelegate = object : GeckoSession.PermissionDelegate {
        override fun onAndroidPermissionsRequest(
            session: GeckoSession,
            permissions: Array<out String>?,
            callback: GeckoSession.PermissionDelegate.Callback,
        ) {
            val missing = permissions.orEmpty().filter {
                checkSelfPermission(it) != PackageManager.PERMISSION_GRANTED
            }
            if (missing.isEmpty()) {
                callback.grant()
                return
            }
            pendingGeckoPermission = callback
            requestPermissions(missing.toTypedArray(), REQ_GECKO_PERMISSIONS)
        }

        override fun onMediaPermissionRequest(
            session: GeckoSession,
            uri: String,
            video: Array<out GeckoSession.PermissionDelegate.MediaSource>?,
            audio: Array<out GeckoSession.PermissionDelegate.MediaSource>?,
            callback: GeckoSession.PermissionDelegate.MediaCallback,
        ) {
            val camera = video?.firstOrNull()
            if (camera != null && uri.startsWith("moz-extension://")) {
                callback.grant(camera, null)
            } else {
                callback.reject()
            }
        }
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray,
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == REQ_GECKO_PERMISSIONS) {
            val callback = pendingGeckoPermission
            pendingGeckoPermission = null
            if (grantResults.isNotEmpty() &&
                grantResults.all { it == PackageManager.PERMISSION_GRANTED }
            ) {
                callback?.grant()
            } else {
                callback?.reject()
            }
        }
    }

    /** Open the wallet UI: its popup document in a dialog over the browser. */
    private fun showWalletPopup(ext: WebExtension) {
        // The user opened the wallet: from here on, wallet-opened tabs
        // (register, sign approvals) are presented.
        walletUserEngaged = true
        walletDialog?.let {
            it.dismiss()
            return
        }
        val base = ext.metaData.baseUrl
        openPopupSession().loadUri("${base}popup.html")
    }

    /** A popup-sized dialog holding a fresh GeckoSession for the wallet UI. */
    private fun openPopupSession(heightFraction: Double = 0.82): GeckoSession {
        // One wallet surface at a time: a tab opened from the popup (register,
        // sign approval) replaces the popup's dialog.
        walletDialog?.dismiss()
        val popupSession = GeckoSession().apply { open(runtime) }
        popupSession.permissionDelegate = walletPermissionDelegate
        val view = GeckoView(this).apply {
            setSession(popupSession)
            // Dark until the wallet page paints (it flashes white otherwise
            // while the bundles parse; the page itself then shows the inline
            // splash from mobile.html).
            coverUntilFirstPaint(COLOR_CHROME_BG)
        }
        // A slim header with an explicit close control: the sheet covers the
        // browser, and the back gesture / tap-outside affordances are not
        // discoverable on their own.
        val closeButton = TextView(this).apply {
            text = "✕"
            textSize = 16f
            setTextColor(COLOR_TEXT)
            gravity = Gravity.CENTER
            contentDescription = "Close wallet"
            setPadding(dp(14), dp(6), dp(14), dp(6))
            setOnClickListener { walletDialog?.dismiss() }
        }
        val header = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            setBackgroundColor(COLOR_CHROME_BG)
            addView(
                TextView(this@MainActivity).apply {
                    text = "Epix Wallet"
                    textSize = 14f
                    setTextColor(COLOR_TEXT)
                    setPadding(dp(16), dp(6), 0, dp(6))
                },
                LinearLayout.LayoutParams(0, -2, 1f),
            )
            addView(closeButton)
        }
        // The wallet popup lays out at the extension-popup size; give it most
        // of the screen (minus the header), dashboard-dark behind it.
        val height = (resources.displayMetrics.heightPixels * heightFraction).toInt() - dp(40)
        val holder = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setBackgroundColor(COLOR_CHROME_BG)
            addView(header, LinearLayout.LayoutParams(-1, -2))
            addView(view, LinearLayout.LayoutParams(-1, height))
        }
        popupSession.contentDelegate = object : GeckoSession.ContentDelegate {
            override fun onCloseRequest(session: GeckoSession) {
                walletDialog?.dismiss()
            }
        }
        // The wallet closes its own pages with tabs.remove (e.g. after
        // registration); treat that like a close request.
        wallet?.let { ext ->
            popupSession.webExtensionController.setTabDelegate(
                ext,
                object : WebExtension.SessionTabDelegate {
                    override fun onCloseTab(
                        source: WebExtension?,
                        session: GeckoSession,
                    ): GeckoResult<org.mozilla.geckoview.AllowOrDeny> {
                        walletDialog?.dismiss()
                        return GeckoResult.allow()
                    }
                },
            )
        }
        val dialog = AlertDialog.Builder(this)
            .setView(holder)
            .create()
        dialog.setOnDismissListener {
            popupSession.close()
            // Only clear the field if it still points at this dialog: when one
            // popup replaces another (popup -> register tab), dismiss() runs
            // its listener asynchronously, so this can fire after the
            // replacement dialog was already stored - clearing it then would
            // drop the reference to the visible dialog and break its close
            // button.
            if (walletDialog === dialog) {
                walletDialog = null
            }
        }
        walletDialog = dialog
        dialog.show()
        // Full width: the wallet pages are laid out for a browser surface, not
        // a margined dialog.
        dialog.window?.setLayout(-1, -2)
        return popupSession
    }

    private fun label(text: String): TextView =
        TextView(this).apply {
            this.text = text
            textSize = 14f
            setPadding(0, dp(4), 0, dp(4))
        }

    /** Flip the clearnet-through-Tor routing, persist it, and apply it live. */
    private fun setTorClearnet(on: Boolean) {
        if (torClearnet == on) return
        torClearnet = on
        getPreferences(Context.MODE_PRIVATE).edit().putBoolean(PREF_TOR_CLEARNET, on).apply()
        applyClearnetRouting()
        // The badge reflects the new routing state at once, not on the next poll.
        torBadge.setColor(if (on) COLOR_ROUTED else COLOR_READY)
    }

    /**
     * Point GeckoView's proxy at the node's Tor SOCKS listener (or direct).
     * When on, all non-loopback (clearnet) requests go through Tor; the node's
     * own loopback - the UI and every `.epix` page served from 127.0.0.1 - is
     * never proxied (allow_hijacking_localhost stays false), so xites keep
     * loading directly. socks_remote_dns keeps DNS inside Tor. This is the
     * runtime equivalent of the desktop launcher's file PAC.
     */
    private fun applyClearnetRouting() {
        val user = GeckoPreferenceController.PREF_BRANCH_USER
        if (torClearnet) {
            GeckoPreferenceController.setGeckoPref("network.proxy.type", 1, user)
            GeckoPreferenceController.setGeckoPref("network.proxy.socks", "127.0.0.1", user)
            GeckoPreferenceController.setGeckoPref("network.proxy.socks_port", SOCKS_PORT, user)
            GeckoPreferenceController.setGeckoPref("network.proxy.socks_version", 5, user)
            GeckoPreferenceController.setGeckoPref("network.proxy.socks_remote_dns", true, user)
            GeckoPreferenceController.setGeckoPref(
                "network.proxy.allow_hijacking_localhost", false, user,
            )
            // Exempt loopback explicitly, the way the desktop PAC returns DIRECT
            // for 127.0.0.1/localhost. Relying on allow_hijacking_localhost
            // alone let the dashboard (served on 127.0.0.1) get routed into the
            // SOCKS proxy, so it hung until Tor finished bootstrapping - a blank
            // screen on first launch. The node's UI and every .epix page load
            // over loopback and must never go through Tor.
            GeckoPreferenceController.setGeckoPref(
                "network.proxy.no_proxies_on", "localhost, 127.0.0.1", user,
            )
        } else {
            GeckoPreferenceController.setGeckoPref("network.proxy.type", 0, user)
        }
    }

    private fun nodeUrl(name: String): String = "$NODE_BASE/$name/"

    private fun dp(v: Int): Int = (v * resources.displayMetrics.density).toInt()

    /** Pull the xite target out of an `epix://host/path` VIEW intent. */
    private fun intentTarget(intent: Intent?): String? {
        val data: Uri = intent?.data ?: return null
        if (data.scheme != "epix") return null
        return data.host ?: data.toString().removePrefix("epix://").substringBefore('/')
    }

    companion object {
        init {
            // The Rust core (libepix_ffi.so, one per ABI) packaged in jniLibs.
            System.loadLibrary("epix_ffi")
        }

        // The node's local Tor SOCKS listener (epix-node boot: 43111).
        private const val SOCKS_PORT = 43111
        private const val PREF_TOR_CLEARNET = "torClearnet"
        private const val PREF_CLEARNET_ALLOW = "clearnetAllow"

        // The embedded node's UI server (bootNode's uiAddr): the EpixNet
        // default port. The app boots the node itself, so unlike the desktop
        // native host there is no discovery/legacy-port fallback to do here.
        private const val UI_PORT = 42222
        /// startActivityForResult request code for a page's file prompt.
        private const val FILE_PICK_REQUEST = 4001
        private const val NODE_BASE = "http://127.0.0.1:$UI_PORT"

        // Must match the wallet manifest's gecko id and its native host name
        // (the desktop crates/epix-browser/src/ext.rs values).
        private const val WALLET_EXT_ID = "wallet@epix.zone"
        private const val NMH_NAME = "zone.epix.nmh"

        // How many failed loads of the node's own UI are retried (each retry
        // first waits for the port) before the inline error page shows.
        private const val MAX_NODE_LOAD_RETRIES = 5

        // Where address-bar searches go. Clearnet, so it follows the
        // clearnet-through-Tor routing like any other non-.epix page.
        private const val SEARCH_BASE = "https://duckduckgo.com/?q="

        // The dashboard's dark chrome + the desktop extension's icon colors.
        private const val REQ_GECKO_PERMISSIONS = 1001
        private val COLOR_CHROME_BG = Color.parseColor("#0b0e14")
        private val COLOR_FIELD_BG = Color.parseColor("#1e293b")
        private val COLOR_TEXT = Color.parseColor("#cbd5e1")
        private val COLOR_HINT = Color.parseColor("#64748b")
        private val COLOR_OFF = Color.parseColor("#64748b")
        private val COLOR_BOOT = Color.parseColor("#f5c450")
        private val COLOR_READY = Color.parseColor("#a78bfa")
        private val COLOR_ROUTED = Color.parseColor("#4ade80")
    }
}
